name: Deploy Langkeyo Portfolio to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install
      
    - name: Build Angular app
      run: pnpm run build --configuration production --base-href /langkeyo-portfolio-angular/
      
    - name: Debug - Check build output
      run: |
        echo "Checking dist folder structure:"
        ls -la dist/
        echo "Looking for index.html files:"
        find dist/ -name "index.html" -type f
      
    - name: Fix Angular SPA routing for GitHub Pages
      run: |
        # Find the actual build output directory
        BUILD_DIR=$(find dist/ -name "index.html" -type f | head -1 | xargs dirname)
        echo "Build directory found: $BUILD_DIR"
        
        # Copy index.html to 404.html for SPA routing
        cp "$BUILD_DIR/index.html" "$BUILD_DIR/404.html"
        echo "Created 404.html for SPA routing"
        
        # Add CNAME for custom domain (optional)
        echo "langkeyo.github.io" > "$BUILD_DIR/CNAME"
        
        # Set environment variable for upload step
        echo "BUILD_PATH=$BUILD_DIR" >> $GITHUB_ENV
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        enablement: true
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.BUILD_PATH }}
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4